name = "TestItems"
uuid = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "1.0.1-DEV"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
